// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TestProject.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20221020031401_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Mark Keeling",
                            JobId = 1,
                            PhoneNumber = "965522022"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Destiny Hays",
                            JobId = 2,
                            PhoneNumber = "685255620"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Lorcan Harrington",
                            JobId = 3,
                            PhoneNumber = "454751215"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Alec Townsend",
                            JobId = 4,
                            PhoneNumber = "582256325"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Jethro Cortes",
                            JobId = 5,
                            PhoneNumber = "215525555"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Dru Black",
                            JobId = 6,
                            PhoneNumber = "126582825"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Claudia Barker",
                            JobId = 7,
                            PhoneNumber = "784446225"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Kunal Farrell",
                            JobId = 8,
                            PhoneNumber = "576652555"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Shaun Burton",
                            JobId = 1,
                            PhoneNumber = "787522552"
                        });
                });

            modelBuilder.Entity("Entities.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Program Manager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Data Analyst"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Inspector"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Operations Manager"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Civil Engineering Intern"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Assistant Process Engineer"
                        },
                        new
                        {
                            Id = 8,
                            Description = "ACCOUNTANT"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Job", "Job")
                        .WithMany("Employees")
                        .HasForeignKey("JobId");
                });
#pragma warning restore 612, 618
        }
    }
}
